CREATE TABLE `aaef_appraisals` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`agentId` int NOT NULL,
	`profileId` int NOT NULL,
	`periodStart` timestamp NOT NULL,
	`periodEnd` timestamp NOT NULL,
	`appraisalDate` timestamp NOT NULL,
	`conductedBy` varchar(255) NOT NULL,
	`d1Score` int NOT NULL,
	`d2Score` int NOT NULL,
	`d3Score` int NOT NULL,
	`d4Score` int NOT NULL,
	`d5Score` int NOT NULL,
	`d1Rationale` text,
	`d2Rationale` text,
	`d3Rationale` text,
	`d4Rationale` text,
	`d5Rationale` text,
	`was` decimal(4,2) NOT NULL,
	`overallRating` enum('exemplary','proficient','developing','at_risk','unacceptable') NOT NULL,
	`overrideTriggered` boolean NOT NULL DEFAULT false,
	`overrideReason` text,
	`improvementPlanRequired` boolean NOT NULL DEFAULT false,
	`quantitativeDataSummary` text,
	`nextAppraisalDate` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `aaef_appraisals_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `aaef_improvement_plans` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`appraisalId` int NOT NULL,
	`agentId` int NOT NULL,
	`dimension` enum('D1','D2','D3','D4','D5','overall') NOT NULL,
	`actionDescription` text NOT NULL,
	`rootCause` text,
	`successCriteria` text,
	`owner` varchar(255) NOT NULL,
	`dueDate` timestamp NOT NULL,
	`checkInDate` timestamp,
	`status` enum('open','in_progress','completed','overdue','escalated') NOT NULL DEFAULT 'open',
	`completedAt` timestamp,
	`completionNote` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `aaef_improvement_plans_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `aaef_profiles` (
	`id` int AUTO_INCREMENT NOT NULL,
	`tenantId` int NOT NULL,
	`profileCode` varchar(8) NOT NULL,
	`profileName` varchar(128) NOT NULL,
	`description` text,
	`w1TaskCompletion` decimal(4,3) NOT NULL DEFAULT '0.25',
	`w2Judgement` decimal(4,3) NOT NULL DEFAULT '0.25',
	`w3Escalation` decimal(4,3) NOT NULL DEFAULT '0.20',
	`w4Compliance` decimal(4,3) NOT NULL DEFAULT '0.20',
	`w5UserExperience` decimal(4,3) NOT NULL DEFAULT '0.10',
	`isDefault` boolean NOT NULL DEFAULT false,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `aaef_profiles_id` PRIMARY KEY(`id`)
);
